id: P006607
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG21278
  title: བདེན་པའི་ལེའུ།
  author: ''
  volumes:
    6b0f7e4b7af44f59b107cf03e39f2246:
      image_group_id: I1KG21325
      title: ''
      volume_number: 1
      total_pages: 254
      base_file: v001.txt
